FROM python:3.12-slim

WORKDIR /app
 
COPY pyproject.toml uv.lock* ./
RUN pip install uv && uv sync
RUN uv pip uninstall redis && uv pip install redis
RUN uv pip install tritonclient[all]

COPY youarebot/ ./youarebot
COPY config/ ./config

CMD uv run uvicorn youarebot.api.main:app --host 0.0.0.0 --port ${SERVICE_PORT} --log-config ./config/logging_config.yaml
