FROM ghcr.io/mlflow/mlflow:v3.5.0

RUN pip install --upgrade pip && \
    pip install psycopg2-binary mlflow[auth] boto3
 
RUN mkdir -p /mlflow_config
COPY basic_auth.ini /mlflow_config/basic_auth.ini
WORKDIR /mlflow_config